### ISSUE TITLE
`UnicodeDecodeError` when installing masonite

### ISSUE THREAD

**Issue by joewalk102** [MasoniteFramework/masonite#229]
**Describe the bug**
I tried to install the latest masonite, 2.3.0 (`python -m pip install masonite`) and an error was raised. 

**To Reproduce**
Setup:
Windows 10, Python3.8, venv

Command: 
`python -m pip install masonite`

**Expected behavior**
I expected the latest version of masonite 2.3.0 to install in my virtual environment.

**Screenshots**

(ok, not really a screenshot.... but.....)

```
Collecting masonite<2.4,>=2.3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f4/00/b7ec4dd823203a6e8c78be83a58d5f4330c0a677b2fae2aa75229df0c0ff/masonite-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Joe\AppData\Local\Temp\pip-install-8xp7w_4r\masonite\setup.py", line 12, in <module>
        readme = f.read()
      File "C:\Users\Joe\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7150: character maps to <undefined>
```

**Additional context**
I backed off to 2.2.31 under python 3.8 and got a different error:
```   generating cffi module 'build\\temp.win32-3.8\\Release\\_constant_time.c'
  generating cffi module 'build\\temp.win32-3.8\\Release\\_openssl.c'
  building '_openssl' extension
  creating build\temp.win32-3.8\Release\build
  creating build\temp.win32-3.8\Release\build\temp.win32-3.8
  creating build\temp.win32-3.8\Release\build\temp.win32-3.8\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Joe\PycharmProjects\DataCollection\venv\include -IC:\Users\Joe\AppData\Local\Programs\Python\Python38-32\include -IC:\Users\Joe\Ap
pData\Local\Programs\Python\Python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcbuild\temp.win32-3.8\Release\_openssl.c /Fobuild\temp.win32-3.8\Release\bui
ld\temp.win32-3.8\Release\_openssl.obj
  _openssl.c
  C:\Users\Joe\AppData\Local\Programs\Python\Python38-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

```
So I started trying other combinations, Python 3.7 & masonite 2.3.0 received the first `UnicodeDecodeError` HOWEVER, Python 3.7 & masonite 2.2.31 does install correctly on my system.

**Comment by josephmancuso** [comment]
#230

**Comment by josephmancuso** [comment]
try now. it was an encoding error. The encoding was not explicitly set on something and there is probably a different default encoding between systems which is why it worked on one machine and not the other

**Comment by joewalk102** [comment]
Passes masonite install, still stuck on cryptography... 

Thanks for the quick response!

**Comment by josephmancuso** [comment]
possibly have an outdated OpenSSL version? https://stackoverflow.com/questions/22073516/failed-to-install-python-cryptography-package-with-pip-and-setup-py
