### ISSUE TITLE
Still looking for orator in Masonite 3

### ISSUE THREAD

**Issue by jpmateo022** [MasoniteFramework/masonite#399]
Hi it seems pydoc is still look for orator in Masonite 3.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/cisco/wsgi.py", line 36, in <module>
    located_provider.load_app(container).register()
  File "/usr/local/lib/python3.8/dist-packages/masonite/providers/AppProvider.py", line 44, in register
    self.app.bind("WebRoutes", flatten_routes(load("routes.web.routes")))
  File "/usr/local/lib/python3.8/dist-packages/masonite/helpers/structures.py", line 219, in load
    return Dot().locate(path, default)
  File "/usr/local/lib/python3.8/dist-packages/masonite/helpers/structures.py", line 109, in locate
    value = self.find(search_path, default)
  File "/usr/local/lib/python3.8/dist-packages/masonite/helpers/structures.py", line 149, in find
    value = pydoc.locate(search_path)
  File "/usr/lib/python3.8/pydoc.py", line 1632, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.8/pydoc.py", line 362, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in routes.web - ModuleNotFoundError: No module named 'orator'
```

**Comment by jpmateo022** [comment]
Update:
It seems masonite-api still uses orator so as a temporary solution until its fixed I override JSONSerializer.

**Comment by girardinsamuel** [comment]
masonite-api is not yet compatible with Masonite 3. This package is actually an old package that might be rewritten entirely.
In the mean time, a patch can be added to at least fix compatibility issues as the one you propose

**Comment by jpmateo022** [comment]
Yeah, I made a pull request at masonite-api section.

https://github.com/MasoniteFramework/api/pull/19

Im going to close this issue since its more on masonite-api.
