### ISSUE TITLE
Cannot execute raw query

### ISSUE THREAD

**Issue by b4oshany** [MasoniteFramework/masonite#431]
**Describe the bug**
I tried to execute a raw query.

**To Reproduce**
```
craft tinker

from config.database import DB
result = DB.statement("select * from users where users.active = 1")
```

error:
```
>>> m = DB.statement("select * from tenants")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/masoniteorm/connections/ConnectionResolver.py", line 117, in statement
    return self.get_query_builder().on(connection).raw(query, bindings)
  File "/usr/local/lib/python3.9/site-packages/masoniteorm/query/QueryBuilder.py", line 345, in __getattr__
    raise AttributeError(
AttributeError: 'QueryBuilder' object has no attribute 'raw'
```

**Comment by girardinsamuel** [comment]
Here you should ge the query builder class with correct connection details as mentioned in the docs here
https://orm.masoniteproject.com/query-builder#getting-the-querybuilder-class
Then you can use `statement()` method on a "connected" query builder instance (https://orm.masoniteproject.com/query-builder#raw-queries):

In your case it should work like this:
```python
from masoniteorm.query import QueryBuilder
result = QueryBuilder().table("users").statement("select * from users where users.active = 1")
```

**Comment by josephmancuso** [comment]
This is actually a code issue. You can see in the stack trace it is calling `self.get_query_builder().on(connection).raw(query, bindings)` when it should be calling `self.get_query_builder().on(connection).statement(query, bindings)`

**Comment by josephmancuso** [comment]
Moving this to the ORM repo
