### ISSUE TITLE
masonite with React fails at command npm run dev

### ISSUE THREAD

**Issue by nakano16180** [MasoniteFramework/masonite#446]
**Describe the bug**

```
[webpack-cli] Error: mix.react() is now a feature flag. Use mix.js(source, destination).react() instead
    at React.register (/home/nakano/workspace/masonite_test/node_modules/laravel-mix/src/components/React.js:36:19)
    at Object.components.<computed> [as react] (/home/nakano/workspace/masonite_test/node_modules/laravel-mix/src/components/ComponentRegistrar.js:133:53)
    at Object.<anonymous> (/home/nakano/workspace/masonite_test/webpack.mix.js:14:5)
    at Module._compile (/home/nakano/workspace/masonite_test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/nakano/workspace/masonite_test/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/home/nakano/workspace/masonite_test/node_modules/laravel-mix/setup/webpack.config.js:8:5)

```

**To Reproduce**
1. mkdir masonite_test && cd $_
2. pipenv install masonite
3. pipenv run craft new .
4. pipenv install -r requirements.txt
5. pipenv run craft preset react
6. npm install && npm run dev

**Comment by Marlysson** [comment]
That's because of an upgrade of Laravel Mix.

Try change to this:

https://laravel-mix.com/docs/6.0/upgrade#api-for-javascript-frameworks

Basically it's change to mix.js(source, destination).react()

**Comment by nakano16180** [comment]
@Marlysson 
Thanks!
I create Pull Request.
