### ISSUE TITLE
Trying to update from masonite 3 to 4

### ISSUE THREAD

**Issue by holic-cl** [MasoniteFramework/masonite#695]
### Describe the bug
Hi!,

I am trying to upgrade my framework from `masonite 3.0.12` to version 4.

After making changes described by [Masonite documentation](https://docs.masoniteproject.com/upgrade-guide/masonite-3.0-to-4.0) i get this error:
```
/path/to/project/venv/lib/python3.10/site-packages/masoniteorm/relationships/BaseRelationship.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.command.build import build
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named ApiController has been found in ['app.controllers.api.v1'] 
Trouble importing controller! No <class 'masonite.controllers.Controller.Controller'> named WelcomeController has been found in ['app.controllers'] 
Traceback (most recent call last):
  File "/path/to/project/craft", line 8, in <module>
    from wsgi import application
  File "/path/to/project/wsgi.py", line 14, in <module>
    application.add_providers(*config("providers.providers"))
  File "/path/to/project/venv/lib/python3.10/site-packages/masonite/foundation/Application.py", line 44, in add_providers
    provider.register()
  File "/path/to/project/venv/lib/python3.10/site-packages/masonite/notification/providers/NotificationProvider.py", line 24, in register
    notification_manager = NotificationManager(self.application).set_configuration(
  File "/path/to/project/venv/lib/python3.10/site-packages/masonite/notification/NotificationManager.py", line 29, in set_configuration
    self.driver_config = config.get("drivers")
AttributeError: 'NoneType' object has no attribute 'get'
```

### OS

Linux

### OS version

Debian Sid

### Masonite Version

3.0.12

**Comment by josephmancuso** [comment]
what's your masonite ORM version?

**Comment by holic-cl** [comment]
Hi @josephmancuso thanks for your reply

I just updated my issue, because i tried some changes and now i got that new error.

i am using masonite-orm version: 2.18.1

**Comment by josephmancuso** [comment]
I'm pushing v2.18.2 now. Looks like a weird import made it into the code. Probably from my auto class importer

**Comment by holic-cl** [comment]
Just updated masonite-orm to v2.18.2 but i still get this error:

```
Traceback (most recent call last):
  File "/path/to/project/craft", line 8, in <module>
    from wsgi import application
  File "/path/to/project/wsgi.py", line 14, in <module>
    application.add_providers(*config("providers.providers"))
  File "/path/to/project/venv/lib/python3.10/site-packages/masonite/foundation/Application.py", line 44, in add_providers
    provider.register()
  File "/path/to/project/venv/lib/python3.10/site-packages/masonite/notification/providers/NotificationProvider.py", line 24, in register
    notification_manager = NotificationManager(self.application).set_configuration(
  File "/path/to/project/venv/lib/python3.10/site-packages/masonite/notification/NotificationManager.py", line 29, in set_configuration
    self.driver_config = config.get("drivers")
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by josephmancuso** [comment]
Check to make sure you have al the right configs https://github.com/MasoniteFramework/cookie-cutter/tree/4.0/config

Also that they are registered correctly as in this file:

https://github.com/MasoniteFramework/cookie-cutter/blob/4.0/Kernel.py#L62
