### ISSUE TITLE
Windows setup not installing

### ISSUE THREAD

**Issue by redeemefy** [MasoniteFramework/masonite#839]
### Describe the bug

I'm following the the blog tutorial in a Windows Home 11 machine and the `pip install masonite` is failing.

```shell
$ python -m pip install masonite
Collecting masonite
  Using cached masonite-4.20.2-py3-none-any.whl
Collecting inflection<0.4,>=0.3 (from masonite)
  Using cached inflection-0.3.1-py3-none-any.whl
Collecting exceptionite<3.0,>=2.2 (from masonite)
  Using cached exceptionite-2.2.5-py3-none-any.whl.metadata (17 kB)
Collecting pendulum<3,>=2 (from masonite)
  Using cached pendulum-2.1.2.tar.gz (81 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting jinja2<3.2 (from masonite)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting cleo<0.9,>=0.8.1 (from masonite)
  Using cached cleo-0.8.1-py2.py3-none-any.whl.metadata (15 kB)
Collecting hupper<1.11,>=1.10 (from masonite)
  Using cached hupper-1.10.3-py2.py3-none-any.whl.metadata (14 kB)
Collecting bcrypt<3.3,>=3.2 (from masonite)
  Using cached bcrypt-3.2.2-cp36-abi3-win_amd64.whl.metadata (8.3 kB)
Collecting whitenoise<5.3,>=5.2 (from masonite)
  Using cached whitenoise-5.2.0-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting python-dotenv<0.16,>=0.15 (from masonite)
  Using cached python_dotenv-0.15.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting masonite-orm<3,>=2.14 (from masonite)
  Using cached masonite_orm-2.23.1-py3-none-any.whl
Collecting hashids<1.4,>=1.3 (from masonite)
  Using cached hashids-1.3.1-py2.py3-none-any.whl.metadata (5.5 kB)
Collecting cryptography<37,>=36 (from masonite)
  Using cached cryptography-36.0.2-cp36-abi3-win_amd64.whl.metadata (5.3 kB)
Collecting tldextract<2.3,>=2.2 (from masonite)
  Using cached tldextract-2.2.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting hfilesize>=0.1 (from masonite)
  Using cached hfilesize-0.1.0-py3-none-any.whl
Collecting dotty_dict<1.40,>=1.3.0 (from masonite)
  Using cached dotty_dict-1.3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting pyjwt<2.5,>=2.4 (from masonite)
  Using cached PyJWT-2.4.0-py3-none-any.whl.metadata (4.1 kB)
Collecting pytest<8,>=7 (from masonite)
  Using cached pytest-7.4.4-py3-none-any.whl.metadata (7.9 kB)
Collecting werkzeug<4,>=3 (from masonite)
  Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting watchdog<=4,>=2 (from masonite)
  Using cached watchdog-4.0.0-py3-none-win_amd64.whl.metadata (37 kB)
Collecting phonenumbers<9,>=8.12 (from masonite)
  Using cached phonenumbers-8.13.50-py2.py3-none-any.whl.metadata (10 kB)
Collecting cffi>=1.1 (from bcrypt<3.3,>=3.2->masonite)
  Using cached cffi-1.17.1-cp312-cp312-win_amd64.whl.metadata (1.6 kB)
Collecting clikit<0.7.0,>=0.6.0 (from cleo<0.9,>=0.8.1->masonite)
  Using cached clikit-0.6.2-py2.py3-none-any.whl.metadata (1.6 kB)
Collecting requests (from exceptionite<3.0,>=2.2->masonite)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: colorama in c:\users\me\workspace\masonite-blog\venv\lib\site-packages (from exceptionite<3.0,>=2.2->masonite) (0.4.6)
Collecting typing-extensions (from exceptionite<3.0,>=2.2->masonite)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting mock (from exceptionite<3.0,>=2.2->masonite)
  Using cached mock-5.1.0-py3-none-any.whl.metadata (3.0 kB)
Collecting MarkupSafe>=2.0 (from jinja2<3.2->masonite)
  Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Collecting faker<14.0,>=4.1.0 (from masonite-orm<3,>=2.14->masonite)
  Using cached Faker-13.16.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in c:\users\me\workspace\masonite-blog\venv\lib\site-packages (from pendulum<3,>=2->masonite) (2.9.0.post0)
Collecting pytzdata>=2020.1 (from pendulum<3,>=2->masonite)
  Using cached pytzdata-2020.1-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting iniconfig (from pytest<8,>=7->masonite)
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: packaging in c:\users\me\workspace\masonite-blog\venv\lib\site-packages (from pytest<8,>=7->masonite) (24.2)
Collecting pluggy<2.0,>=0.12 (from pytest<8,>=7->masonite)
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting idna (from tldextract<2.3,>=2.2->masonite)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting requests-file>=1.4 (from tldextract<2.3,>=2.2->masonite)
  Using cached requests_file-2.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting pycparser (from cffi>=1.1->bcrypt<3.3,>=3.2->masonite)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting crashtest<0.4.0,>=0.3.0 (from clikit<0.7.0,>=0.6.0->cleo<0.9,>=0.8.1->masonite)
  Using cached crashtest-0.3.1-py3-none-any.whl.metadata (748 bytes)
Collecting pastel<0.3.0,>=0.2.0 (from clikit<0.7.0,>=0.6.0->cleo<0.9,>=0.8.1->masonite)
  Using cached pastel-0.2.1-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting pylev<2.0,>=1.3 (from clikit<0.7.0,>=0.6.0->cleo<0.9,>=0.8.1->masonite)
  Using cached pylev-1.4.0-py2.py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\me\workspace\masonite-blog\venv\lib\site-packages (from python-dateutil<3.0,>=2.6->pendulum<3,>=2->masonite) (1.16.0)
Collecting charset-normalizer<4,>=2 (from requests->exceptionite<3.0,>=2.2->masonite)
  Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting urllib3<3,>=1.21.1 (from requests->exceptionite<3.0,>=2.2->masonite)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->exceptionite<3.0,>=2.2->masonite)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Using cached bcrypt-3.2.2-cp36-abi3-win_amd64.whl (29 kB)
Using cached cleo-0.8.1-py2.py3-none-any.whl (21 kB)
Using cached cryptography-36.0.2-cp36-abi3-win_amd64.whl (2.2 MB)
Using cached dotty_dict-1.3.1-py3-none-any.whl (7.0 kB)
Using cached exceptionite-2.2.5-py3-none-any.whl (484 kB)
Using cached hashids-1.3.1-py2.py3-none-any.whl (6.6 kB)
Using cached hupper-1.10.3-py2.py3-none-any.whl (26 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached phonenumbers-8.13.50-py2.py3-none-any.whl (2.6 MB)
Using cached PyJWT-2.4.0-py3-none-any.whl (18 kB)
Using cached pytest-7.4.4-py3-none-any.whl (325 kB)
Using cached python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Using cached tldextract-2.2.3-py2.py3-none-any.whl (48 kB)
Using cached watchdog-4.0.0-py3-none-win_amd64.whl (82 kB)
Using cached werkzeug-3.1.3-py3-none-any.whl (224 kB)
Using cached whitenoise-5.2.0-py2.py3-none-any.whl (19 kB)
Using cached cffi-1.17.1-cp312-cp312-win_amd64.whl (181 kB)
Using cached clikit-0.6.2-py2.py3-none-any.whl (91 kB)
Using cached Faker-13.16.0-py3-none-any.whl (1.6 MB)
Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl (15 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached mock-5.1.0-py3-none-any.whl (30 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl (102 kB)
Using cached crashtest-0.3.1-py3-none-any.whl (7.0 kB)
Using cached pastel-0.2.1-py2.py3-none-any.whl (6.0 kB)
Using cached pylev-1.4.0-py2.py3-none-any.whl (6.1 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: pendulum
  Building wheel for pendulum (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pendulum (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\me\AppData\Local\Temp\pip-install-mn3afapg\pendulum_75f7aea1a82a4d6aa89bae82bee31fa7\build.py", line 5, in <module>
          from distutils.command.build_ext import build_ext
      ModuleNotFoundError: No module named 'distutils'
      Traceback (most recent call last):
        File "C:\Users\me\Workspace\masonite-blog\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\me\Workspace\masonite-blog\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\me\Workspace\masonite-blog\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\me\AppData\Local\Temp\pip-build-env-d1ngyg36\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\me\AppData\Local\Temp\pip-build-env-d1ngyg36\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\me\AppData\Local\Temp\pip-build-env-d1ngyg36\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 123, in build
          self._build(zip_file)
        File "C:\Users\me\AppData\Local\Temp\pip-build-env-d1ngyg36\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 172, in _build
          self._run_build_script(self._package.build_script)
        File "C:\Users\me\AppData\Local\Temp\pip-build-env-d1ngyg36\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 262, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "C:\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:/Users/me/Workspace/masonite-blog/venv/Scripts/python.exe', 'build.py']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pendulum
Failed to build pendulum
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pendulum)
```

### Expected behaviour

To get a fresh masonite installation.

### Steps to reproduce the bug

1. Have a Windows Home 11
2. Install python 3.12.6 with choco
3. Create directory for project
4. Create `python -3.12 -m venv venv`
5. `source ./venv/Scripts/activate`
6. `python -m pip install --upgrade pip setuptools`
7. `python -m pip install masonite`

### OS

Windows

### OS version

Version	10.0.26100 Build 26100

### Browser

N/A

### Masonite Version

4.6.1

**Comment by amitavroy** [comment]
@redeemefy  I know it's late, but I had similar issue and that's how I ran into your issue.

Based on the provided error output, the reason for the installation failure is that the distutils module is missing from your Python environment. The pendulum package, which is a dependency of masonite, is trying to build a wheel, but its build script fails because it cannot find distutils.
