### ISSUE TITLE
Generated Auth Errs on Register Route

### ISSUE THREAD

**Issue by aisola** [MasoniteFramework/masonite#84]
When a user tries to register for a user account in the browser, the generated authentication system throws an error resulting in a 500 response code. However, it appears as though the user is correctly created and saved in the database. Stack trace is below.

Misc Info:
Ubuntu 14.04
Python 3.4.3
Everything is pip installed into a virtualenv.

Reproduction steps:
* Generate new project and `cd` into it
* Run `python3 -m venv venv` and `source venv/bin/activate`
* Run `pip install -r requirements`
* Run `craft auth`
* Run `craft migrate`
* Run `craft serve`
* Go to `localhost:8000/register` and try to create user. I used the following details: username = demo, email = demo@example.com, password = password.

Full console output, including stack trace:
```Serving on http://localhost:8000
GET Route: /register
POST Route: /register
ERROR:waitress:Exception when serving /register
Traceback (most recent call last):
  File "/home/acisola/workspace/python3/test-project/bootstrap/start.py", line 49, in app
    container.resolve(located_provider.boot)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/app.py", line 65, in resolve
    return obj(*provider_list)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/providers/RouteProvider.py", line 113, in boot
    response = self.app.resolve(route.output)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/app.py", line 65, in resolve
    return obj(*provider_list)
  File "/home/acisola/workspace/python3/test-project/app/http/controllers/RegisterController.py", line 32, in store
    if Auth(Request).login(Request.input(auth.AUTH['model'].__auth__), Request.input('password')):
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/facades/Auth.py", line 52, in login
    raise exception
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/facades/Auth.py", line 44, in login
    if model and bcrypt.checkpw(bytes(password, 'utf-8'), bytes(model.password, 'utf-8')):
TypeError: encoding or errors without a string argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/home/acisola/workspace/python3/test-project/bootstrap/start.py", line 51, in app
    container.make('ExceptionHandler').load_exception(e)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/exception_handler.py", line 28, in load_exceptio
n
    self._render()
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/exception_handler.py", line 48, in _render
    'open': open
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/view.py", line 79, in render
    self.dictionary)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/acisola/workspace/python3/test-project/venv/lib/python3.4/site-packages/masonite/snippets/exception.html", line 62, in top-level 
template code
    {% for i, line in enumerate(open(stack.filename)) %}
TypeError: Can't convert 'Undefined' object to str implicitly```

**Comment by josephmancuso** [comment]
Ok thanks I'll look into this in a bit! Thanks for reporting.

**Comment by aisola** [comment]
Oh, sorry. I did run craft install. I missed writing that down. Though, my environment got a bit messed up so I ended up re-running pip install. I'll try it again anyway and report back.

**Comment by josephmancuso** [comment]
Awesome Thanks! I have a feeling it will throw the same error so just let
me know


On May 2, 2018 at 3:35 PM, <Abram C. Isola <notifications@github.com>>
wrote:

Oh, sorry. I did run craft install. I missed writing that down. Though, my
environment got a bit messed up so I ended up re-running pip install. I'll
try it again anyway and report back.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MasoniteFramework/masonite/issues/84#issuecomment-386094754>,
or mute the thread

**Comment by josephmancuso** [comment]
ok great so I tested on my Mac python 3.6 so let me just load up my ubuntu virtual box to run some tests

**Comment by aisola** [comment]
Just tested it here as well. Same result. I did have some issues with the craft command, but it still generated the .env file and got most of the way through the pip install. I was able to fix the pip issues manually. So, I don't think that the command failure has anything to do with it.

**Comment by josephmancuso** [comment]
what were the pip issues? did something not install fully?

**Comment by aisola** [comment]
Craft install failed with:

```Traceback (most recent call last):
  File "/home/acisola/workspace/python3/test-masonite/venv/bin/craft", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/acisola/workspace/python3/test-masonite/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/home/acisola/workspace/python3/test-masonite/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/home/acisola/workspace/python3/test-masonite/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3099, in _initialize$
master_working_set
    working_set = WorkingSet._build_master()
  File "/home/acisola/workspace/python3/test-masonite/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 576, in _build_maste$
    return cls._build_from_requirements(__requires__)
  File "/home/acisola/workspace/python3/test-masonite/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 589, in _build_from_$
equirements
    dists = ws.resolve(reqs, Environment())
  File "/home/acisola/workspace/python3/test-masonite/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cleo==0.6.4' distribution was not found and is required by masonite-cli```

Running `craft install` actually tried to install `cleo==0.6.5` which caused the craft command to throw the Distribution not found error because of the specific version requirement. After that manually installing 0.6.4 fixed the issue as you would expect, however, that same issue occurs whenever I run `craft install`.

**Comment by josephmancuso** [comment]
ok great looking into this now. slightly annoying to have multiple python versions on a virtual machine lol

**Comment by josephmancuso** [comment]
hm.. strange. I tested with ubuntu and 3.5 and seems to be working fine. let me run a few more tests

**Comment by aisola** [comment]
Okay, a lot more info on my end. So, my craft install issues were totally caused by my environment (and multiple python version installs as you mentioned). I got that figured out by manually shimming the right python version and now I have *no problems* with the craft utility. (I manually did what setuptools does when you set the `console_scripts` entrypoint in setup.py).

So `craft install` works without a hitch.

However, the auth issue still persists in a fresh install. Though I realized the real issue here. The one thing I really neglected to mention. This whole time, for simplicity I decided to change the database configuration for orator. I use orator pretty commonly outside of masonite which is what lead me to beleive that changing the config wouldn't have much of an effect on the rest of the framework. Evidently I was wrong. I've been using the sqlite driver. Using the MySQL driver, I don't have this issue at all, it works as expected/advertised.

So this seems to be a database specific issue (though I haven't tested with postgres either).

**Comment by josephmancuso** [comment]
oh interesting so this issue can be closed? I want to put questions like this somewhere though ..

So correct me if i'm wrong:

Using the Mysql driver, everything works fine but using a the sqlite driver, it fails? If so i'll test that out on my mac right now

**Comment by aisola** [comment]
That's correct. Using MySQL, everything works as expected. Using sqlite, it fails with the above traceback. 

In my opinion, it's probably a good idea to keep this issue open until it does get fixed (though we can change the title to be more specific now). I imagine that since I had this problem, some other dev could come along and make the same assumption. Unless there's some other place to put it, I would say keep the issue open.

However, this also begs the question: Do you want to support MySQL, Postgres, and sqlite? (much like Django and Laravel). If not, then the issue can be closed. If so, then I this issue should remain open until it's fixed for both Sqlite and Postgres.

Ultimately, it's up to you. This comment is just my opinion as a random internet user. :smile:

**Comment by josephmancuso** [comment]
@aisola Found it!

Apparently if you send bytes to Mysql, it will automatically convert it to a string before inserting into database.

Postgres and, I assume, sqlite does not. Thats why there was the string line in the exception

you can patch this yourself by changing ~line 20 in the register controller to:

```python
        password = bytes(bcrypt.hashpw(
            bytes(Request.input('password'), 'utf-8'), bcrypt.gensalt()
        )).decode('utf-8')
```

**Comment by aisola** [comment]
Got it! It works as expected now for both MySQL and Sqlite.

Thanks for the help!

**Comment by josephmancuso** [comment]
Thanks for your help is solving this, I'll push out a 1.6.3 release. Please let me know of anything else you find and how you like the framework
